<?php

/*
=====================================================
 Copyright (c) 2022-2024 MrDeath && Timmy
=====================================================
 This code is protected by copyright
=====================================================
*/

if( ! defined( 'DATALIFEENGINE' ) ) {
	die( "Hacking attempt!" );
}

$data_list = array( "shikimori_id", "shikimori_name", "shikimori_russian", "shikimori_english", "shikimori_japanese", "shikimori_synonyms", "shikimori_license_name_ru", "shikimori_licensors", "shikimori_kind", "shikimori_kind_ru", "shikimori_score", "shikimori_votes", "shikimori_status", "shikimori_status_ru", "shikimori_episodes", "shikimori_tv_length", "shikimori_episodes_aired", "shikimori_episodes_aired_1", "shikimori_episodes_aired_2", "shikimori_episodes_aired_3", "shikimori_episodes_aired_4", "shikimori_episodes_aired_5", "shikimori_episodes_aired_6", "shikimori_episodes_aired_7", "shikimori_episodes_aired_8", "shikimori_aired_on", "shikimori_aired_on_2", "shikimori_aired_on_3", "shikimori_aired_on_4", "shikimori_released_on", "shikimori_released_on_2", "shikimori_released_on_3", "shikimori_released_on_4", "shikimori_year", "shikimori_season", "shikimori_rating", "shikimori_duration", "shikimori_duration_2", "shikimori_duration_3", "shikimori_duration_4", "shikimori_duration_length", "shikimori_plot", "shikimori_genres", "shikimori_studios", "shikimori_videos", "myanimelist_id", "official_site", "wikipedia", "anime_news_network", "anime_db", "world_art", "kinopoisk", "kage_project", "shikimori_director", "shikimori_producer", "shikimori_script", "shikimori_composition", "shikimori_franshise", "shikimori_similar", "shikimori_related", "shikimori_chronology", "worldart_country", "worldart_plot", "worldart_tags", "worldart_rating", "worldart_votes", "youtube_trailer", "myanimelist_rating", "myanimelist_votes" );
$data_list_kodik = array( "shikimori_id", "mydramalist_id", "image", "kadr_1", "kadr_2", "kadr_3", "kadr_4", "kadr_5", "kodik_title", "kodik_title_orig", "kodik_other_title", "kodik_year", "kodik_worldart_link", "kodik_mydramalist_tags", "kodik_status_en", "kodik_status_ru", "kodik_status_en_voice", "kodik_status_ru_voice", "kodik_status_en_sub", "kodik_status_ru_sub", "kodik_status_en_autosub", "kodik_status_ru_autosub", "kodik_premiere_ru", "kodik_premiere_ru_2", "kodik_premiere_ru_3", "kodik_premiere_ru_4", "kodik_premiere_world", "kodik_premiere_world_2", "kodik_premiere_world_3", "kodik_premiere_world_4", "kodik_iframe", "kodik_quality", "kodik_kinopoisk_id", "kodik_imdb_id", "kodik_translation", "kodik_translation_last", "kodik_translation_types", "kodik_translation_types_ru", "kodik_tagline", "kodik_plot", "kodik_next_episode_at", "kodik_duration", "kodik_duration_2", "kodik_duration_3", "kodik_duration_4", "kodik_duration_length", "kodik_video_type", "kodik_countries", "kodik_genres", "kodik_kinopoisk_rating", "kodik_kinopoisk_votes", "kodik_imdb_rating", "kodik_imdb_votes", "kodik_mydramalist_rating", "kodik_mydramalist_votes", "kodik_minimal_age", "kodik_rating_mpaa", "kodik_actors", "kodik_directors", "kodik_producers", "kodik_writers", "kodik_composers", "kodik_editors", "kodik_designers", "kodik_operators", "kodik_last_season", "kodik_last_season_1", "kodik_last_season_2", "kodik_last_season_3", "kodik_last_season_4", "kodik_last_season_5", "kodik_last_season_6", "kodik_last_season_7", "kodik_last_season_8", "kodik_last_season_translated", "kodik_last_season_subtitles", "kodik_last_season_autosubtitles", "kodik_last_episode", "kodik_last_episode_1", "kodik_last_episode_2", "kodik_last_episode_3", "kodik_last_episode_4", "kodik_last_episode_5", "kodik_last_episode_6", "kodik_last_episode_7", "kodik_last_episode_8", "kodik_last_episode_translated", "kodik_last_episode_subtitles", "kodik_last_episode_autosubtitles", "kodik_episodes_total", "kodik_tv_length", "kodik_episodes_aired", "catalog_rus", "catalog_eng" );